categories:
- Proteomics
description: Proteomics Datatypes
long_description: |
  Proteomics Datatypes
name: proteomics_datatypes
owner: iracooke
remote_repository_url: https://github.com/iracooke/proteomics-datatypes
type: unrestricted
